### ISSUE TITLE
Support for Mac ARM support

### ISSUE THREAD

**Issue by normj** [awslabs/aws-crt-dotnet#75]
Attempting to test out the CRT HTTP .NET bindings but failed on M1 Mac with the following error message. Can we get Mac ARM supported added?

```
System.TypeInitializationException: The type initializer for 'API' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Aws.Crt.NativeAPI' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Aws.Crt.CRT' threw an exception.
 ---> System.InvalidOperationException: Unable to load , exception occurred
 ---> System.IO.IOException: Could not find libaws-crt-dotnet-ARM64.dylib in resource manifest; Resources=Aws.CRT.libaws-crt-dotnet-ARM64.so,Aws.CRT.libaws-crt-dotnet-x64.so,Aws.CRT.aws-crt-dotnet-x64.dll,Aws.CRT.aws-crt-dotnet-x86.dll,Aws.CRT.libaws-crt-dotnet-x64.dylib
   at Aws.Crt.CRT.PlatformBinding.ExtractLibrary(String libraryName)
   at Aws.Crt.CRT.PlatformBinding..ctor()
   --- End of inner exception stack trace ---
   at Aws.Crt.CRT.PlatformBinding..ctor()
   at Aws.Crt.CRT..cctor()
   --- End of inner exception stack trace ---
   at Aws.Crt.CRT.get_Binding()
   at Aws.Crt.NativeAPI..cctor()
   --- End of inner exception stack trace ---
   at Aws.Crt.NativeAPI.BindImpl[D](String nativeFunctionName)
   at Aws.Crt.NativeAPI.Bind[D]()
   at Aws.Crt.IO.TlsContext.API..cctor()
   --- End of inner exception stack trace ---
   at Aws.Crt.IO.ClientTlsContext..ctor(TlsContextOptions options)
```

**Comment by graebm** [comment]
Fixed in 0.3.19!
